[project]
requires-python = ">= 3.11"


[tool.black]
line-length = 80

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict = true
namespace_packages=true

[tool.pylsp-mypy]
enabled = true
live_mode = true
strict = true
namespace_packages=true